print('\033[1;97;40m              ANALISADOR DE STRING              \033[m')
n1 = input('Digite algo: ')
print('\033[0;30;107m O tipo primitivo desse dado é: ',type(n1),  '\033[m')
print('Só tem espaços: ',n1.isspace())
print('É um número? ',n1.isnumeric())
print('Está com inicial maiuscula?',n1.istitle())
print('Está tudo em caixa alta?',n1.isupper())
print('Está tudo em minusculo?',n1.islower())
print('É uma palavra?',n1.isalpha())
print('É um dado alfanumérico?','\033[1;32;107m',n1.isalnum(),'\033[m')
