nome = str(input('Nome completo: ')).strip()
print('Analisando seu nome ...')
print('Seu nome em letra maiuscula é: \033[4;30;107m{} \033[m' .format(nome.upper()))
print('Seu nome em letra minuscula é: {} ' .format(nome.lower()))
print('A quantidade de letras do seu nome é {} '.format(len(nome)-nome.count(' ')))
dividido=nome.split()
#print('Seu primeiro nome tem {} letras'.format(nome.find(' ')))
print(dividido)
print('Seu primeiro nome é {} e ele tem {} letras'.format(dividido[0],len(dividido[0])))
