nome=input('Qual é o seu nome?')
idade=input('Qual a sua idade?')
peso=input('Qual é o seu peso?')
print(nome,idade,peso)
print('É um grande prazer te conhecer',nome)
endereço=input('Onde você mora?')
dia=input('Que dia vc nasceu?')
mês=input('Qual mês vc nasceu?')
ano=input('Qual ano vc nasceu?')
print('Então, você nasceu em ',dia,'de',mês,'de',ano,'correto?')
