n=input('Digite algo:')
print(n)
print(type(n))
print(n.isnumeric())
print(n.isalpha())
print(n.isalnum())
print(n.isascii())
print(n.isdigit())
print(n.isdecimal())
print(n.isidentifier())
print(n.islower())
print(n.isprintable())
print(n.isspace())
print(n.istitle())
print(n.isupper())
